export const ENDPOINTS = {
  auth: {
    requestVerification: '/auth/request-verification',
    verify: '/auth/verify',
    password: '/auth/password',
    me: '/auth/me',
    resetPassword: '/auth/reset-password',
  },
  ai: {
    chat: '/ai/chat',
    models: '/ai/models',
    status: '/ai/status',
  },
  intelligence: {
    health: '/intelligence/health',
    status: '/intelligence/status',
    analyze: '/intelligence/analyze',
  },
  settings: {
    get: '/settings',
    save: '/settings',
    aiHealth: '/settings/ai-health',
  },
  admin: {
    workspaces: '/admin/workspaces',
    updateSubscription: (tenantId: string) => `/admin/workspaces/${tenantId}/subscription`,
    workspaceGroups: (tenantId: string) => `/admin/workspaces/${tenantId}/groups`,
    updateWorkspaceGroup: (tenantId: string, groupJid: string) => `/admin/workspaces/${tenantId}/groups/${encodeURIComponent(groupJid)}`,
    impersonate: (tenantId: string) => `/admin/workspaces/${tenantId}/impersonate`,
    resolveImpersonation: (token: string) => `/admin/impersonation/resolve?token=${encodeURIComponent(token)}`,
    revokeImpersonation: (token: string) => `/admin/impersonation/${encodeURIComponent(token)}`,
    impersonations: '/admin/impersonations',
    audit: '/admin/audit',
  },
  workspace: {
    overview: '/workspace/overview',
    team: '/workspace/team',
    updateMember: (memberId: string) => `/workspace/team/${memberId}`,
    activity: '/workspace/activity',
  },
  whatsapp: {
    connect: '/whatsapp/connect',
    disconnect: '/whatsapp/disconnect',
    status: '/whatsapp/status',
    sessions: '/whatsapp/sessions',
    qr: '/whatsapp/qr',
    monitor: '/whatsapp/monitor',
    inbox: '/whatsapp/inbox',
    health: '/whatsapp/health',
    groupsHealth: '/whatsapp/groups/health',
    events: '/whatsapp/events',
    profile: '/whatsapp/profile',
    qrForceRefresh: '/whatsapp/qr/force-refresh',
    groups: '/whatsapp/groups',
    parseTargets: '/whatsapp/parse-targets',
    parseConsent: '/whatsapp/parse-consent',
    recipients: '/whatsapp/recipients',
    broadcast: '/whatsapp/broadcast',
    messages: '/whatsapp/messages',
    sendBulk: '/whatsapp/send-bulk',
  },
  channels: {
    list: '/channels',
    create: '/channels',
    stream: '/channels/stream',
    analytics: '/channels/analytics',
    rebuild: '/channels/stream/rebuild',
    correct: (streamItemId: string) => `/channels/stream/${streamItemId}/correct`,
    markRead: (channelId: string) => `/channels/${channelId}/read`,
    attachItem: (channelId: string) => `/channels/${channelId}/items`,
  },
  streamItems: {
    list: '/stream-items',
    read: (streamItemId: string) => `/stream-items/${streamItemId}/read`,
    correct: (streamItemId: string) => `/stream-items/${streamItemId}/correct`,
    stats: '/stream-items/stats',
  },
  properties: {
    search: (query: string) => `/properties/search?q=${encodeURIComponent(query)}`,
  },
} as const;
