export const ROUTE_PATHS = {
  api: {
    auth: '/api/auth',
    whatsapp: '/api/whatsapp',
    channels: '/api/channels',
    broadcast: '/api/broadcast',
    workspace: '/api/workspace',
    ai: '/api/ai',
    agent: '/api/agent',
    admin: '/api/admin',
    voice: '/api/voice',
    settings: '/api/settings',
    voiceListen: '/api/voice/listen',
    health: '/health',
    propertiesSearch: '/api/properties/search',
    aiPropertySearch: '/api/ai/property-search',
  },
  channels: {
    root: '/',
    stream: '/stream',
    rebuild: '/stream/rebuild',
    correct: '/stream/:streamItemId/correct',
    markRead: '/:channelId/read',
    attachItem: '/:channelId/items',
    analytics: '/analytics',
  },
  broadcast: {
    parse: '/parse',
  },
  auth: {
    requestVerification: '/request-verification',
    verify: '/verify',
    password: '/password',
    me: '/me',
    refresh: '/refresh',
    resetPassword: '/reset-password',
  },
   whatsapp: {
     connect: '/connect',
     qr: '/qr',
     qrForceRefresh: '/qr/force-refresh',
     status: '/status',
     monitor: '/monitor',
     inbox: '/inbox',
     health: '/health',
     healthDetailed: '/health/detailed',
     groupsHealth: '/groups/health',
     events: '/events',
     profile: '/profile',
     messages: '/messages',
     send: '/send',
     sendBulk: '/send-bulk',
     broadcast: '/broadcast',
     disconnect: '/disconnect',
     groups: '/groups',
     parseTargets: '/parse-targets',
     parseConsent: '/parse-consent',
     recipients: '/recipients',
     config: '/config',
   },
  ai: {
    chat: '/chat',
    status: '/status',
    models: '/models',
    keys: '/keys',
    keysTest: '/keys/test',
    propertySearch: '/property-search',
  },
  agent: {
    webFetch: '/tool/web_fetch',
    storeLeads: '/tool/store_leads',
  },
  admin: {
    workspaces: '/workspaces',
    updateSubscription: '/workspaces/:tenantId/subscription',
    workspaceGroups: '/workspaces/:tenantId/groups',
    updateWorkspaceGroup: '/workspaces/:tenantId/groups/:groupJid',
  },
  workspace: {
    overview: '/overview',
    team: '/team',
    updateMember: '/team/:memberId',
    activity: '/activity',
  },
  voice: {
    speak: '/speak',
    listen: '/listen',
  },
} as const;
